name: Build FFmpeg Exoplayer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: "21.4.7075529"  # Ganti dengan versi NDK yang stabil
      EXOPLAYER: "r2.19.1"
      FFMPEG: "release/4.4"
    steps:
    - name: Set up checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -qq commandlinetools-linux-7583922_latest.zip
        mkdir -p android-sdk/cmdline-tools && mv cmdline-tools $_/latest
        export ANDROID_HOME=$PWD/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export NDK_PATH=$ANDROID_HOME/ndk/$ANDROID_NDK
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo y | sdkmanager --update >> log.txt
        echo y | sdkmanager --install "ndk;$ANDROID_NDK" >> log.txt

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build with gradle
      run: |
        set -e
        export NDK_PATH=$ANDROID_NDK_HOME
        export HOST_PLATFORM="linux-x86_64"
        export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        git clone -b $EXOPLAYER https://github.com/google/ExoPlayer.git
        export FFMPEG_MODULE_PATH=$PWD/ExoPlayer/extensions/ffmpeg/src/main
        pushd $FFMPEG_MODULE_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg
        ./build_ffmpeg.sh $FFMPEG_MODULE_PATH $NDK_PATH $HOST_PLATFORM ${ENABLED_DECODERS[@]}
        popd
        pushd ExoPlayer
        ./gradlew :extension-ffmpeg:assembleRelease

    - name: Copy FFmpeg to folder
      run: |
        mkdir -p Exoplayer/ffmpeg-libs
        find . -name "*.aar" -exec cp {} Exoplayer/ffmpeg-libs/ \;

    - name: Commit and push changes
      run: |
        git pull
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Exoplayer/ffmpeg-libs
        git commit -m "Add FFmpeg libs" || echo "No changes to commit"
        git push

    - name: Upload as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-aar
        path: Exoplayer/ffmpeg-libs/*.aar
