name: Build FFmpeg Exoplayer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: "21.4.7075529"
      EXOPLAYER: "r2.19.1"
      FFMPEG: "release/7.0"
      ANDROID_ABI: 21
      YOUR_REPO: "https://github.com/evileye19/test.git"  # Ganti dengan URL repo Anda
      YOUR_BRANCH: "main"  # Ganti dengan branch yang berisi build_ffmpeg.sh
    steps:
    - name: Set up checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install NDK
      run: |
        echo y | sdkmanager --update >> log.txt
        echo y | sdkmanager --install "ndk;$ANDROID_NDK" >> log.txt
        
    - name: Install pkg-config
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config

    - name: Build FFmpeg
      run: |
        set -e
        export NDK_PATH=$ANDROID_HOME/ndk/$ANDROID_NDK
        export HOST_PLATFORM="linux-x86_64"
        export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        git clone -b $EXOPLAYER https://github.com/google/ExoPlayer.git
        export FFMPEG_MODULE_PATH=$PWD/ExoPlayer/extensions/ffmpeg/src/main
        pushd $FFMPEG_MODULE_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg

        # Clone your repo and copy build_ffmpeg.sh and ffmpeg_jni.cc
        git clone -b $YOUR_BRANCH $YOUR_REPO test-clone
        cp test-clone/build_ffmpeg.sh ./build_ffmpeg.sh
        cp test-clone/ffmpeg_jni.cc ./ffmpeg_jni.cc
        
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh $FFMPEG_MODULE_PATH $NDK_PATH $HOST_PLATFORM $ANDROID_ABI ${ENABLED_DECODERS[@]}
        popd
        pushd ExoPlayer
        ./gradlew :extension-ffmpeg:assembleRelease

    - name: Copy FFmpeg to folder
      run: |
        mkdir -p Exoplayer/ffmpeg-libs
        find . -name "*.aar" -exec cp {} Exoplayer/ffmpeg-libs/ \;

    - name: Commit and push changes
      run: |
        git pull
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Exoplayer/ffmpeg-libs
        git commit -m "Add FFmpeg libs" || echo "No changes to commit"
        git push

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-aar
        path: Exoplayer/ffmpeg-libs/*.aar
