name: Build FFmpeg Exoplayer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: "21.4.7075529"
      EXOPLAYER: "r2.19.1"
      FFMPEG: "release/7.0"
    steps:
    - name: Set up checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install NDK
      run: |
        sdkmanager --install "ndk;${{ env.ANDROID_NDK_VERSION }}"
    - name: Build with Gradle
      run: |
        set -e
        export NDK_PATH=$ANDROID_NDK_HOME
        export HOST_PLATFORM="linux-x86_64"
        export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        git clone -b $EXOPLAYER https://github.com/google/ExoPlayer.git
        export FFMPEG_EXT_PATH=$PWD/ExoPlayer/extensions/ffmpeg/src/main
        pushd $FFMPEG_EXT_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg
        # Modify build_ffmpeg.sh
        sed -i 's/--disable-avresample//' build_ffmpeg.sh
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh $FFMPEG_EXT_PATH $NDK_PATH $HOST_PLATFORM ${ENABLED_DECODERS[@]}
        popd
    - name: Build AAR
      run: |
        cd media
        ./gradlew :extension-ffmpeg:assembleRelease
    - name: Copy FFmpeg to folder
      run: |
        mkdir -p Exoplayer/ffmpeg-libs
        cp ExoPlayer/extensions/ffmpeg/buildout/outputs/aar/extension-ffmpeg-release.aar Exoplayer/ffmpeg-libs/
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Exoplayer/ffmpeg-libs
        git commit -m "Add FFmpeg libs" || echo "No changes to commit"
        git push
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-aar
        path: Exoplayer/ffmpeg-libs/extension-ffmpeg-release.aar
