name: Build Ffmpeg Media3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: "21.4.7075529"
      MEDIA3: "1.4.1"
      FFMPEG: "release/5.0"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: |
        set -e  # Exit on any error
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -qq commandlinetools-linux-7583922_latest.zip
        mkdir -p android-sdk/cmdline-tools && mv cmdline-tools $_/latest
        export ANDROID_HOME=$PWD/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export NDK_PATH=$ANDROID_HOME/ndk/$ANDROID_NDK
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo y | sdkmanager --update >> log.txt
        echo y | sdkmanager --install "ndk;$ANDROID_NDK" >> log.txt
        git clone -b $MEDIA3 https://github.com/androidx/media.git
        export FFMPEG_EXT_PATH=$PWD/media/libraries/decoder_ffmpeg/src/main
        export HOST_PLATFORM="linux-x86_64"
        export ENABLED_DECODERS=(opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd vorbis)
        export ANDROID_ABIS="armeabi-v7a arm64-v8a x86 x86_64"
        echo "FFMPEG_EXT_PATH: $FFMPEG_EXT_PATH"
        echo "NDK_PATH: $NDK_PATH"
        echo "HOST_PLATFORM: $HOST_PLATFORM"
        echo "ENABLED_DECODERS: ${ENABLED_DECODERS[@]}"
        echo "ANDROID_ABIS: $ANDROID_ABIS"
        pushd $FFMPEG_EXT_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh $FFMPEG_EXT_PATH $NDK_PATH $HOST_PLATFORM $ANDROID_ABIS ${ENABLED_DECODERS[@]}
        popd
        pushd $FFMPEG_EXT_PATH/jni/ffmpeg
        ./configure --help
        popd
        # Assuming ExoPlayer is in your repository
        pushd ExoPlayer
        ./gradlew :extension-ffmpeg:assembleRelease
        popd
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: extension-ffmpeg-release.aar
        path: ExoPlayer/extension-ffmpeg/build/outputs/aar/extension-ffmpeg-release.aar
