name: Build FFmpeg Media3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: "21.4.7075529"
      MEDIA3: "1.4.1"
      FFMPEG: "release/7.0"
      ANDROID_ABI: 21
    steps:
    - name: Set up checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install NDK
      run: |
        sdkmanager --install "ndk;${{ env.ANDROID_NDK_VERSION }}"
    - name: Install pkg-config
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config
    - name: Build FFmpeg Media3
      run: |
        set -e
        export NDK_PATH=$ANDROID_NDK_HOME
        export HOST_PLATFORM="linux-x86_64"
        export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        git clone -b $MEDIA3 https://github.com/androidx/media.git
        export FFMPEG_EXT_PATH=$PWD/media/libraries/decoder_ffmpeg/src/main
        pushd $FFMPEG_EXT_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh $FFMPEG_EXT_PATH $NDK_PATH $HOST_PLATFORM $ANDROID_ABI ${ENABLED_DECODERS[@]}
        popd
    - name: Build with gradle
      run: |
        cd media
        ./gradlew :libraries:decoder_ffmpeg:assembleRelease
    - name: Copy FFmpeg to folder
      run: |
        mkdir -p Exoplayer/ffmpeg-libs
        cp media/libraries/decoder_ffmpeg/build/outputs/aar/decoder_ffmpeg-release.aar Exoplayer/ffmpeg-libs/
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Exoplayer/ffmpeg-libs
        git commit -m "Add FFmpeg libs" || echo "No changes to commit"
        git push
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-aar
        path: Exoplayer/ffmpeg-libs/decoder_ffmpeg-release.aar
